name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # v로 시작하는 태그를 푸시하면 실행 (예: v0.1.0)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - uses: actions/checkout@v3

      # 2. 파이썬 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. 빌드 툴 설치
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # 4. 패키지 빌드
      - name: Build package
        run: python -m build

      # 5. PyPI로 업로드
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.8
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
